### ISSUE TITLE
Добавить доступ командующим ролям десанта.

### ISSUE THREAD

**Issue by 778b** [FFATroop/TroopStation14#21]
**Описание**
Создать доступ по аналогии с уже имеющемуся доступом в игре. И добавить его PartCommander и PlatoonCommander
Пример доступа можете найти по адресу: TroopStation14\Resources\Prototypes\Access
Роли десанта находятся по адресу: TroopStation14\Resources\Prototypes\TS\Roles\Combat
Название для доступа: TroopCommander
Прототип доступа должен находится по адресу: TroopStation14\Resources\Prototypes\TS\Access

**Comment by Brian123123Origin** [comment]
На легко бы сделал да вот только я сильный
