### ISSUE TITLE
Отображение кол-ва патронов для плазмоганов

### ISSUE THREAD

**Issue by 778b** [FFATroop/TroopStation14#48]
**Описание**
Хз какой компонент за это отвечает, возможно решается вместе с #44. Сейчас когда держишь его в руках то у тебя не отображается кол-во патронов, как у обычных пушек.

**Comment by AwareFoxy** [comment]
За это AmmoCounter отвечает в прото 
(Тип `type: AmmoCounter` )

**Comment by 778b** [comment]
> За это AmmoCounter отвечает в прото (Тип `type: AmmoCounter` )

К сожелению, AmmoCounter уже есть у плазмоганов, но патроны не отображаются, потому что у ProjectileBatteryAmmoProvider нет подписки на ивент AmmoCounterControlEvent и не отправляются никакие циферки в GunSystem поэтому это надо будет кому-то дописать, или мне
